apiVersion: v2
name: icat-k8s
version: 1.1.0
description: A Helm chart for deploying ICAT core components on Kubernetes
type: application
keywords:
  - icat
  - data-catalogue
  - open-data
home: https://github.com/ALBA-Synchrotron/icat-k8s
sources:
  - https://github.com/ALBA-Synchrotron/icat-k8s
icon: https://alba-synchrotron.github.io/icat-k8s/icat-k8s-logo.png
maintainers:
  - name: Rodrigo Cabezas Quirós (MIS section @ ALBA Synchrotron)
icon: https://public.cells.es/cdn/public/icat/icat-k8s-logo.png
