FROM registry.cells.es/docker/payara/server-full:6.2025.3-jdk21

ARG NEW_UID=1000
ARG NEW_GID=1000

USER root

# Change UID and GID for payara user to allow NFS mount
RUN addgroup --gid $NEW_GID badassfish
RUN adduser --home /opt/payara/ --shell /bin/sh --no-create-home --uid $NEW_UID --gid $NEW_GID --disabled-login --gecos "" badassfish

# Fix permissions
RUN find / -path /proc -prune -o -user payara -exec chown -R badassfish:badassfish {} \;

USER badassfish