namespace: "icat-core-test"
environment: "test"

images:
  broker: "registry.cells.es/docker/apache/activemq-artemis:2.40.0"
  container:
    micro: "registry.cells.es/mis/icat/payara/micro:6.2025.2-jdk21"
    serverFull: "registry.cells.es/mis/icat/payara/server-full:6.2025.3-jdk21"
  initContainers:
    # Must be image running as root (need to install curl)
    python: "registry.cells.es/docker/python:3.12.9-bullseye"
    curl: "registry.cells.es/docker/curlimages/curl:8.13.0"

imagePullSecretName: "harbor-registry-key"

artifacts:
  rootRepositoryURL: "https://misdockerprod02.cells.es/nexus/repository/icat-alba"
  databaseConnector:
    artifactPath: "/org/icatproject/mariadb-java-client/3.5.2/mariadb-java-client-3.5.2.jar"
    filename: "mariadb-java-client.jar"
    type: "lib"
    #repositoryURL: "https://youcanoverridethisifyouwant.nice"
  activeMQRAR:
    artifactPath: "/org/apache/activemq/activemq-rar/6.1.6/activemq-rar-6.1.6.rar"
    filename: "activemq-rar.rar"
    type: "rar"
    #repositoryURL: "https://youcanoverridethisifyouwant.nice"
  elasticAPM:
    artifactPath: "/elastic/elastic-apm-agent/1.50.0/elastic-apm-agent-1.50.0.jar"
    filename: "elastic-apm-agent.jar"
    type: "lib"
    #repositoryURL: "https://youcanoverridethisifyouwant.nice"
  idsStorageFile:
    artifactPath: "/org/icatproject/ids.storage_file_alba/1.4.4_ALBA/ids.storage_file_alba-1.4.4_ALBA.jar"
    filename: "ids-storage_file_alba.jar"
    type: "lib"
  icatProjectComponents:
    baseArtifactPath: "/org/icatproject/"
    #repositoryURL: "https://youcanoverridethisifyouwant.nice"
  initScripts:
    url: "https://git.cells.es/mis-devops/icat-public/icat-k8s/-/raw/master/setup_scripts"

setupPropertiesSecretName: "icat-core-setup-properties"
runPropertiesSecretMapName: "icat-core-run-properties"
oaipmhXSLTConfigMapName: "icat-core-oaipmh-xslt"
logbackConfigMapName: "icat-core-logback"
brokerConfigSecretName: "icat-core-broker-config"

deploymentPriorityClassName: "icat-priority"

elasticAPM:
  enabled: true
  apm:
    serviceNamePrefix: "icat-core"
    serverUrl: "https://kubeelasticmis.cells.es/apm"
    apmLogSending: true
    secretTokenSecretName: "elastic-apm-token"

broker:
  enabled: false
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.5"
  readinessProbe:
    tcpSocket:
      port: 61616
    failureThreshold: 5
    periodSeconds: 10
  livenessProbe:
    tcpSocket:
      port: 61616
    failureThreshold: 5
    periodSeconds: 10

components:
  # authn.anon -- ANONYMOUS AUTHENTICATION COMPONENT
  - name: "authn-anon"
    containerType: "micro"
    repoKey: "authn.anon"
    version: "3.0.0"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      requests:
        memory: "500Mi"
    readinessProbe:
      httpGet:
        path: "/authn.anon/version"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/authn.anon/version"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: false
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
    additionalArtifacts:
      - elasticAPM
  # authn.db -- DATABASE AUTHENTICATION COMPONENT
  - name: "authn-db"
    containerType: "micro"
    repoKey: "authn.db"
    version: "3.0.0"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      requests:
        memory: "500Mi"
    readinessProbe:
      httpGet:
        path: "/authn.db/version"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/authn.db/version"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: false
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
      - logback
    additionalArtifacts:
      - elasticAPM
      - databaseConnector
    # authn.oidc -- OPENID CONNECT AUTHENTICATION COMPONENT
  - name: "authn-oidc"
    containerType: "micro"
    repoKey: "authn.oidc"
    version: "2.0.1"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      requests:
        memory: "500Mi"
    readinessProbe:
      httpGet:
        path: "/authn.oidc/version"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/authn.oidc/version"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: false
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
    additionalArtifacts:
      - elasticAPM
  # authn.oaipmh -- OAI-PMH (Open Archive Initiative-Protocol for Metadata Harvesting) COMPONENT
  - name: "icat-oaipmh"
    containerType: "micro"
    repoKey: "icat.oaipmh"
    version: "2.0.1"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      requests:
        memory: "500Mi"
    readinessProbe:
      httpGet:
        path: "/oaipmh/version"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/oaipmh/version"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: false
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
      - logback
      - oaipmh-xslt
    additionalArtifacts:
      - elasticAPM
    startupDependencies:
      - name: "icat-server"
        path: "/icat/version/"
        port: 8080
  # icat.server -- ICAT SERVER COMPONENT
  - name: "icat-server"
    containerType: "serverFull"
    repoKey: "icat.server"
    version: "6.1.0"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      limits:
        memory: "12Gi"
        cpu: "4.0"
      requests:
        memory: "6Gi"
        cpu: "1.0"
    readinessProbe:
      httpGet:
        path: "/icat/version/"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/icat/version/"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: false
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
      - logback
    additionalArtifacts:
      - elasticAPM
      - databaseConnector
    startupDependencies:
      - name: "authn-db"
        path: "/authn.db/version"
        port: 8080
      - name: "authn-anon"
        path: "/authn.anon/version"
        port: 8080
      - name: "authn-oidc"
        path: "/authn.oidc/version"
        port: 8080
  # ids.server -- ICAT DATA SERVICE (IDS) SERVER COMPONENT
  - name: "ids-server"
    containerType: "serverFull"
    repoKey: "ids.server"
    version: "2.1.1"
    replicas: 1
    secretTokenSecretName: "elastic-apm-token"
    resources:
      limits:
        memory: "12Gi"
        cpu: "4.0"
      requests:
        memory: "6Gi"
        cpu: "1.0"
    readinessProbe:
      httpGet:
        path: "/ids/ping/"
        port: 8080
      failureThreshold: 1
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: "/ids/ping/"
        port: 8080
      periodSeconds: 20
    mountInstrumentStorage: true
    optionalVolumesSecretsAndConfigMapsMounts:
      - run-properties
      - setup-properties
      - logback
      - cache-dir
    additionalArtifacts:
      - elasticAPM
      - idsStorageFile
    startupDependencies:
      - name: "icat-server"
        path: "/icat/version/"
        port: 8080

instrumentStorage:
  #mountPrefix: "/data"
  storageList:
  - name: bl01 # NCD-SWEET
    mountPath: /beamlines/bl01
    readOnly: true
    nfs:
      server: beamlines01.cells.es
      path: /beamlines/bl01
      readOnly: true
  - name: bl11 # MIRAS
    mountPath: /beamlines/bl11
    readOnly: true
    nfs:
      path: /beamlines/bl11
      server: beamlines01.cells.es
      readOnly: true
  - name: bl20 # LOREA
    mountPath: /beamlines/bl20
    readOnly: true
    nfs:
      path: /beamlines/bl20
      server: beamlines02.cells.es
      readOnly: true
  - name: bl24 # CIRCE
    mountPath: /beamlines/bl24
    readOnly: true
    nfs:
      path: /beamlines/bl24
      server: beamlines02.cells.es
      readOnly: true
  - name: bl13 # XALOC
    mountPath: /beamlines/bl13
    readOnly: true
    nfs:
      path: /beamlines/bl13
      server: beamlines02.cells.es
      readOnly: true
  - name: bl16 # NOTOS
    mountPath: /beamlines/bl16
    readOnly: true
    nfs:
      path: /beamlines/bl16
      server: beamlines02.cells.es
      readOnly: true
  - name: bl09 # MISTRAL
    mountPath: /beamlines/bl09
    readOnly: true
    nfs:
      path: /beamlines/bl09
      server: beamlines01.cells.es
      readOnly: true
  - name: bl06 # XAIRA
    mountPath: /beamlines/bl06
    readOnly: true
    nfs:
      path: /instruments/bl06
      server: ufs.cells.es
      readOnly: true
  - name: bl29 # BOREAS
    mountPath: /beamlines/bl29
    readOnly: true
    nfs:
      path: /beamlines/bl29
      server: beamlines02.cells.es
      readOnly: true
  - name: bl31 # FAXTOR
    mountPath: /beamlines/bl31
    readOnly: true
    nfs:
      path: /instruments/bl31
      server: ufs.cells.es
      readOnly: true