apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: icat-core-logback-{{ $.Release.Name }}
  labels:
    app: icat
    tier: core
    release: {{ $.Release.Name }}
data:
{{- range $.Values.components }}
  {{ .name }}: {{ .logbackXml | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: icat-core-xslt-{{ $.Release.Name }}
  labels:
    app: icat
    tier: core
    release: {{ $.Release.Name }}
data:
{{- range $.Values.components }}
  {{- if .xslt }}
  {{- range .xslt }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
  {{- end}}
  {{- end}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: icat-core-synonym-txt-{{ $.Release.Name }}
  labels:
    app: icat
    tier: core
    release: {{ $.Release.Name }}
data:
{{- range $.Values.components }}
  {{- if .synonymTxt }}
  {{- range .synonymTxt }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
  {{- end}}
  {{- end}}
{{- end }}
