{{- range $.Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.global.namespace }}
  name: icat-core-{{ .name}}-deployment-{{ $.Values.global.environment }}
  labels:
    app: icat
    env: {{ $.Values.global.environment }}
    tier: core
    component: {{ .name }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: icat
      env: {{ $.Values.global.environment }}
      tier: core
      component: {{ .name }}
      release: {{ $.Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: icat
        env: {{ $.Values.global.environment }}
        tier: core
        component: {{ .name }}
        release: {{ $.Release.Name }}
    spec:
      priorityClassName: icat-priority
      initContainers:
        - name: init-{{ .name }}-{{ $.Values.global.environment }}-setup
          image: {{ $.Values.global.images.initContainer.python }}
          env:
            - name: DASH_PWD
              value: "Present Working Dilemma"
            {{- if .requiresBroker}}
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.brokerConfigSecretName }}-{{ $.Values.global.environment }}
                  key: username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.brokerConfigSecretName }}-{{ $.Values.global.environment }}
                  key: password
            - name: BROKER_HOST
              value: icat-core-broker-service-{{ $.Values.global.environment }}
            {{- end}}
          command:
            - "sh"
            - "-c"
            - |
              {{- if $.Values.elasticAPM.enabled }}
              curl -o /opt/payara/libs/elastic-apm-agent.jar {{ $.Values.global.artifacts.repositoryURL }}/elastic/elastic-apm-agent/{{ $.Values.elasticAPM.version }}/elastic-apm-agent-{{ $.Values.elasticAPM.version }}.jar && \
              {{- end }}
              curl -o /opt/payara/deployments/{{.repoKey}}-{{.version}}.war {{ $.Values.global.artifacts.repositoryURL }}/org/icatproject/{{ .repoKey }}/{{ .version }}/{{ .repoKey }}-{{ .version }}.war && \
              {{- if .includeDatabaseJar }}
              curl -o /opt/payara/libs/{{ $.Values.global.artifacts.databaseConnector.name }}-{{ $.Values.global.artifacts.databaseConnector.version }}.jar {{ $.Values.global.artifacts.repositoryURL }}/org/icatproject/{{ $.Values.global.artifacts.databaseConnector.name }}/{{ $.Values.global.artifacts.databaseConnector.version }}/{{ $.Values.global.artifacts.databaseConnector.name }}-{{ $.Values.global.artifacts.databaseConnector.version }}.jar && \
              {{- end }}
              {{- if .requiresBroker}}
                curl -o /opt/payara/rar/activemq-rar.rar {{ $.Values.global.artifacts.repositoryURL }}{{$.Values.broker.rar.groupPath}}{{$.Values.broker.rar.artifactId}}/{{$.Values.broker.rar.version}}/{{$.Values.broker.rar.artifactId}}-{{$.Values.broker.rar.version}}.rar && \
              {{- end }}
              curl -L -o /opt/payara/deployments/icat_k8s_setup_generator.py {{ $.Values.global.initScriptsURL }}/icat_k8s_setup_generator.py && \
              curl -L -o /opt/payara/deployments/icat_k8s_setup_utils.py {{ $.Values.global.initScriptsURL }}/icat_k8s_setup_utils.py && \
              cd /opt/payara/deployments/ && \
              python /opt/payara/deployments/icat_k8s_setup_generator.py --component {{ .repoKey }}
          volumeMounts:
            - name: shared-deployments-dir
              mountPath: /opt/payara/deployments
            - name: shared-libs-dir
              mountPath: /opt/payara/libs
            {{- if .hasSetupProperties }}
            - name: setup-properties
              mountPath: /opt/payara/deployments/setup.properties
              subPath: setup.properties
            {{- end }}
            {{- if .hasRunProperties }}
            - name: run-properties
              mountPath: /opt/payara/deployments/run.properties
              subPath: run.properties
            {{- end }}
            {{- if .hasLogback }}
            - name: logback-xml
              mountPath: /opt/payara/deployments/logback.xml
              subPath: logback.xml
            {{- end }}
            {{- if .hasExternalXSLT }}
            - name: external-xslt
              mountPath: /opt/payara/xslt/
            {{- end }}
            {{- if .requiresBroker}}
            - name: rar-dir
              mountPath: /opt/payara/rar/
            {{- end}}
        {{- if .startupDependencies }}

        - name: init-{{ $.Values.global.environment }}-wait-for-dependent-svc-availability
          image: {{ $.Values.global.images.initContainer.curl }}
          command:
            - "sh"
            - "-c"
            - |
              urls="
              {{- range .startupDependencies }}
              http://icat-core-{{ .name}}-service-{{ $.Values.global.environment }}:8080{{ .path }}
              {{- end }}
              "
              while true; do
                all_ok=true

                for url in $urls; do
                  status=$(curl -sw '%{http_code}' --max-time 5 "$url" -o /dev/null)
                  echo "Checking $url - Status: $status"

                  if [ "$status" -ne 200 ]; then
                    all_ok=false
                  fi
                done

                if [ "$all_ok" = true ]; then
                  break
                fi

                echo "Waiting 5s before retrying..."
                sleep 5
              done
              echo "✅ All services are up!"

        {{- end }}
      containers:
        - image: {{ $.Values.global.images.container }}
          imagePullPolicy: Always
          command:
            # The creation of the glassfish-acc.xml is necessary for the ICAT server to run as otherwise will
            # fail to detect the container type and will not start (see following file, function at line 27):
            # https://github.com/icatproject/icat.utils/blob/master/src/main/java/org/icatproject/utils/ContainerGetter.java
            - "sh"
            - "-c"
            - |
              touch /opt/payara/glassfish-acc.xml && \
              java \
              {{- if $.Values.elasticAPM.enabled }}
              -javaagent:/opt/payara/libs/elastic-apm-agent.jar \
              -Delastic.apm.service_name=icat-core-{{ .name}}-{{ $.Values.global.environment }} \
              -Delastic.apm.application_packages=es.cells.icat.authn_alba,org.icatproject.authn_anon,org.icatproject.authn_db,org.icatproject.icat_oaipmh,org.icatproject.exposed,org.icatproject.ids \
              {{- end }}
              -jar /opt/payara/payara-micro.jar \
              --addlibs /opt/payara/libs/ \
              --postbootcommandfile /opt/payara/deployments/post_boot_asadmin_commands \
              --deploydir /opt/payara/deployments/
          env:
            - name: DASH_PWD
              value: "Present Working Dilemma"
            {{- if $.Values.elasticAPM.enabled }}
            - name: ELASTIC_APM_LOG_SENDING
              value:  "{{ $.Values.elasticAPM.apm.apmLogSending }}"
            - name: ELASTIC_APM_ENVIRONMENT
              value: {{ $.Values.global.environment }}
            - name: ELASTIC_APM_SERVER_URL
              value: {{ $.Values.elasticAPM.apm.serverUrl }}
            - name: APM_SERVICE_NAME
              value: icat-core-{{ .name}}-{{ $.Values.global.environment }}
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticAPM.apm.secretTokenSecretName }}
                  key: token
            {{- end }}
          name: icat-core-{{ .name}}-{{ $.Values.global.environment }}
          ports:
            - containerPort: 8080
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .mountInstrumentStorage }}
          {{- range $.Values.instrumentStorage }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          - name: shared-deployments-dir
            mountPath: /opt/payara/deployments/
          - name: shared-libs-dir
            mountPath: /opt/payara/libs/
          {{- if .requiresBroker}}
          - name: rar-dir
            mountPath: /opt/payara/rar/
          {{- end}}
          {{- if .hasExternalXSLT }}
          - name: external-xslt
            mountPath: /opt/payara/xslt/
          {{- end}}
      restartPolicy: Always
      volumes:
        - name: shared-deployments-dir
          emptyDir: {}
        - name: shared-libs-dir
          emptyDir: {}
        {{- if .requiresBroker}}
        - name: rar-dir
          emptyDir: {}
        {{- end}}
        {{- if .hasSetupProperties }}
        - name: setup-properties
          secret:
            secretName: {{ $.Values.global.setupPropertiesSecretName }}-{{ $.Values.global.environment }}
            items:
              - key: {{.name}}
                path: setup.properties
        {{- end}}
        {{- if .hasRunProperties }}
        - name: run-properties
          configMap:
            name: {{ $.Values.global.runPropertiesConfigMapName }}-{{ $.Values.global.environment }}
            items:
              - key: {{.name}}
                path: run.properties
        {{- end }}
        {{- if .hasLogback }}
        - name: logback-xml
          configMap:
            name: {{ $.Values.global.logbackConfigMapName }}-{{ $.Values.global.environment }}
            items:
            - key: {{.name}}
              path: logback.xml
        {{- end }}
        {{- if .hasExternalXSLT }}
        - name: external-xslt
          configMap:
            name: {{ $.Values.global.oaipmhXSLTConfigMapName }}-{{ $.Values.global.environment }}
        {{- end }}
        {{- if .mountInstrumentStorage }}
        {{- range $.Values.instrumentStorage }}
        - name: {{ .name }}
        {{- if .nfs }}
          nfs:
          {{- toYaml .nfs | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
status: {}
---
{{- end }}
