{{- range $.Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.global.namespace }}
  name: icat-core-{{ .name}}-deployment-{{ $.Values.global.environment }}
  labels:
    app: icat
    env: {{ $.Values.global.environment }}
    component: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: icat
      env: {{ $.Values.global.environment }}
      component: {{ .name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: icat
        env: {{ $.Values.global.environment }}
        component: {{ .name }}
    spec:
      priorityClassName: icat-priority
      initContainers:
        - name: init-{{ .name }}-{{ $.Values.global.environment }}-setup
          image: {{ $.Values.global.images.initContainer.python }}
          command:
            - "sh"
            - "-c"
            - |
              {{- if $.Values.elasticAPM.enabled }}
              curl -o /opt/payara/libs/elastic-apm-agent.jar {{ $.Values.global.artifacts.repositoryURL }}/elastic/elastic-apm-agent/{{ $.Values.elasticAPM.version }}/elastic-apm-agent-{{ $.Values.elasticAPM.version }}.jar && \
              {{- end }}
              curl -o /opt/payara/deployments/{{.repoKey}}-{{.version}}.war {{ $.Values.global.artifacts.repositoryURL }}/org/icatproject/{{ .repoKey }}/{{ .version }}/{{ .repoKey }}-{{ .version }}.war && \
              {{- if .includeDatabaseJar }}
              curl -o /opt/payara/libs/{{ $.Values.global.artifacts.databaseConnector.name }}-{{ $.Values.global.artifacts.databaseConnector.version }}.jar {{ $.Values.global.artifacts.repositoryURL }}/org/icatproject/{{ $.Values.global.artifacts.databaseConnector.name }}/{{ $.Values.global.artifacts.databaseConnector.version }}/{{ $.Values.global.artifacts.databaseConnector.name }}-{{ $.Values.global.artifacts.databaseConnector.version }}.jar && \
              {{- end }}
              curl -L -o /opt/payara/deployments/icat_k8s_setup_generator.py {{ $.Values.global.initScriptsURL }}/icat_k8s_setup_generator.py && \
              curl -L -o /opt/payara/deployments/icat_k8s_setup_utils.py {{ $.Values.global.initScriptsURL }}/icat_k8s_setup_utils.py && \
              cd /opt/payara/deployments/ && \
              python /opt/payara/deployments/icat_k8s_setup_generator.py --component {{ .repoKey }}
          volumeMounts:
            - name: shared-deployments-dir
              mountPath: /opt/payara/deployments
            - name: shared-libs-dir
              mountPath: /opt/payara/libs
            {{- if .hasSetupProperties }}
            - name: setup-properties
              mountPath: /opt/payara/deployments/setup.properties
              subPath: setup.properties
            {{- end }}
            {{- if .hasRunProperties }}
            - name: run-properties
              mountPath: /opt/payara/deployments/run.properties
              subPath: run.properties
            {{- end }}
      containers:
        - image: {{ $.Values.global.images.container }}
          imagePullPolicy: Always
          command:
            - "java"
            {{- if $.Values.elasticAPM.enabled }}
            - "-javaagent:/opt/payara/libs/elastic-apm-agent.jar"
            - "-Delastic.apm.service_name=icat-core-{{ .name}}-{{ $.Values.global.environment }}"
            - "-Delastic.apm.application_packages=es.cells.icat.authn_alba,org.icatproject.authn_anon,org.icatproject.authn_db,org.icatproject.icat_oaipmh,org.icatproject.exposed,org.icatproject.ids"
            {{- end }}
            - "-jar"
            - "/opt/payara/payara-micro.jar"
            - "--addlibs"
            - "/opt/payara/libs/"
            - "--postbootcommandfile"
            - "/opt/payara/deployments/post_boot_asadmin_commands"
            - "--deploydir"
            - "/opt/payara/deployments/"
          env:
            - name: DASH_PWD
              value: "Present Working Dilemma"
            {{- if $.Values.elasticAPM.enabled }}
            - name: ELASTIC_APM_LOG_SENDING
              value:  "{{ $.Values.elasticAPM.apm.apmLogSending }}"
            - name: ELASTIC_APM_ENVIRONMENT
              value: {{ $.Values.global.environment }}
            - name: ELASTIC_APM_SERVER_URL
              value: {{ $.Values.elasticAPM.apm.serverUrl }}
            - name: APM_SERVICE_NAME
              value: icat-core-{{ .name}}-{{ $.Values.global.environment }}
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticAPM.apm.secretTokenSecretName }}
                  key: token
            {{- end }}
          name: icat-core-{{ .name}}-{{ $.Values.global.environment }}
          ports:
            - containerPort: 8080
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .mountInstrumentStorage }}
          {{- range $.Values.instrumentStorage }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
          {{- if .hasSetupProperties }}
          - name: setup-properties
            mountPath: /opt/payara/deployments/setup.properties
            subPath: setup.properties
          {{- end }}
          {{- if .hasRunProperties }}
          - name: run-properties
            mountPath: /opt/payara/deployments/run.properties
            subPath: run.properties
          {{- end }}
          - name: shared-deployments-dir
            mountPath: /opt/payara/deployments/
          - name: shared-libs-dir
            mountPath: /opt/payara/libs/
      restartPolicy: Always
      volumes:
        - name: shared-deployments-dir
          emptyDir: {}
        - name: shared-libs-dir
          emptyDir: {}
        {{- if .hasSetupProperties }}
        - name: setup-properties
          secret:
            secretName: {{ $.Values.global.setupPropertiesSecretName }}-{{ $.Values.global.environment }}
            items:
              - key: {{.name}}
                path: setup.properties
        {{- end}}
        {{- if .hasRunProperties }}
        - name: run-properties
          configMap:
            name: {{ $.Values.global.runPropertiesConfigMapName }}-{{ $.Values.global.environment }}
            items:
              - key: {{.name}}
                path: run.properties
        {{- end }}
        {{- if .mountInstrumentStorage }}
        {{- range $.Values.instrumentStorage }}
        - name: {{ .name }}
        {{- if .nfs }}
          nfs:
          {{- toYaml .nfs | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
status: {}
---
{{- end }}
