apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: icat-core-setup-properties-{{ $.Values.environment }}-{{ $.Release.Name }}
  labels:
    app: icat
    env: {{ $.Values.environment }}
    tier: core
    release: {{ $.Release.Name }}
type: Opaque
stringData:
{{- range $.Values.components }}
  {{ .name }}: {{ .setupProperties | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: icat-core-run-properties-{{ $.Values.environment }}-{{ $.Release.Name }}
  labels:
    app: icat
    env: {{ $.Values.environment }}
    tier: core
    release: {{ $.Release.Name }}
type: Opaque
stringData:
  {{- range $.Values.components }}
    {{ .name }}: {{ .runProperties | quote }}
  {{- end }}