apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: icat-core-setup-properties-{{ $.Release.Name }}
  labels:
    app: icat
    tier: core
    release: {{ $.Release.Name }}
type: Opaque
stringData:
{{- range $.Values.components }}
  {{ .name }}: {{ .setupProperties | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: icat-core-run-properties-{{ $.Release.Name }}
  labels:
    app: icat
    tier: core
    release: {{ $.Release.Name }}
type: Opaque
stringData:
  {{- range $.Values.components }}
    {{ .name }}: {{ .runProperties | quote }}
  {{- end }}