{{- range $.Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: icat
    env: {{ $.Values.global.environment }}
    tier: core
    component: {{ .name }}
  name: icat-core-{{ .name}}-service-{{ $.Values.global.environment }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: icat
    env: {{ $.Values.global.environment }}
    tier: core
    component: {{ .name }}
status:
  loadBalancer: {}
{{- end }}