{{- range $.Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  labels:
    app: icat
    tier: core
    component: {{ .name }}
    release: {{ $.Release.Name }}
  name: icat-core-{{ .name}}-service-{{ $.Release.Name }}
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: icat
    tier: core
    component: {{ .name }}
    release: {{ $.Release.Name }}
status:
  loadBalancer: { }
{{- end }}