{{- range $.Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace }}
  labels:
    app: icat
    env: {{ $.Values.environment }}
    tier: core
    component: {{ .name }}
    release: {{ $.Release.Name }}
  name: icat-core-{{ .name}}-service-{{ $.Values.environment }}-{{ $.Release.Name }}
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: icat
    env: {{ $.Values.environment }}
    tier: core
    component: {{ .name }}
    release: {{ $.Release.Name }}
status:
  loadBalancer: { }
{{- end }}